copyright: Copyright (c) Ultraviolet
repo_url: https://github.com/ultravioletrs/cocos
site_description: Cocos AI SMPC Platform
site_name: Cocos AI
site_url: https://docs.cocos.ai
edit_uri: ""
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  - TEE: tee.md
  - Computation: computation.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Manager: manager.md
  - Agent: agent.md
  - CLI: cli.md
  - HAL: hal.md
  - Attestation: attestation.md
  - Developer's Guide: developer-guide.md
